name: Build FIELD_PROG_Debug

on:
  workflow_dispatch

jobs:
  build_FIELD_PROG_Debug:
    name: Build FIELD_PROG_Debug
    uses: ./.github/workflows/skyworks_evb_build.yaml
    with:
      targetName: 'FIELD_PROG_Debug'
